//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsStudent
    {
        public int GR_No { get; set; }
        public string status { get; set; }
        public System.DateTime Month { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
